name: CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]


jobs:
  build:
    name: Build ai-service
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: api
      FOLDER: ai-service
    defaults:
      run:
        working-directory: ${{ env.FOLDER }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Convert github repository name to lowercase
        run: echo "IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Convert github registry name to lowercase
        run: echo "IMAGE_REGISTRY=$(echo ${{ env.REGISTRY }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV && ls -al

      - name: Login to GitHub Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.FOLDER }}
          file: ./${{ env.FOLDER }}/Dockerfile
          push: true
          tags: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}-${{ env.IMAGE_NAME }}:latest
